// <auto-generated />
using System;
using FridgeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FridgeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FridgeApp.Entities.Fridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fridges");
                });

            modelBuilder.Entity("FridgeApp.Entities.FridgeQuickAddItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FridgeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("QuickAmounts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TrackingType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductDefinitionId");

                    b.ToTable("FridgeQuickAddItems");
                });

            modelBuilder.Entity("FridgeApp.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ApproximateStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FridgeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductDefinitionId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("TrackingType")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FridgeApp.Entities.ItemActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FridgeId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductDefinitionId")
                        .HasColumnType("integer");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ItemActivityLogs");
                });

            modelBuilder.Entity("FridgeApp.Entities.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuickAdd")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuickAmounts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .HasColumnType("text");

                    b.Property<int>("TrackingType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProductDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kahvaltilik",
                            DefaultUnit = "adet",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Yumurta",
                            QuickAmounts = "[6,10,12,15,20,30]",
                            TrackingType = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sut Urunleri",
                            DefaultUnit = "litre",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Sut",
                            QuickAmounts = "[0.5,1,2]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sut Urunleri",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Yogurt",
                            QuickAmounts = "[250,500,1000]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kahvaltilik",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Peynir",
                            QuickAmounts = "[100,250,500]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Kahvaltilik",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Tereyagi",
                            QuickAmounts = "[100,250,500]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "Et ve Tavuk",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Tavuk",
                            QuickAmounts = "[250,500,1000]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Et ve Tavuk",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Kiyma",
                            QuickAmounts = "[250,500,1000]",
                            TrackingType = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sebze",
                            DefaultUnit = "adet",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Domates",
                            QuickAmounts = "[2,4,6,8]",
                            TrackingType = 2
                        });
                });

            modelBuilder.Entity("FridgeApp.Entities.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("FridgeApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstallId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FridgeApp.Entities.FridgeQuickAddItem", b =>
                {
                    b.HasOne("FridgeApp.Entities.Fridge", null)
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeApp.Entities.ProductDefinition", null)
                        .WithMany()
                        .HasForeignKey("ProductDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
