// <auto-generated />
using System;
using FridgeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FridgeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415054121_AddProductCatalogSupport")]
    partial class AddProductCatalogSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FridgeApp.Entities.Fridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fridges");
                });

            modelBuilder.Entity("FridgeApp.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FridgeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductDefinitionId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FridgeApp.Entities.ProductDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuickAdd")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickAmounts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kahvaltilik",
                            DefaultUnit = "adet",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Yumurta",
                            QuickAmounts = "[6,10,12,15,20,30]"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sut Urunleri",
                            DefaultUnit = "litre",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Sut",
                            QuickAmounts = "[0.5,1,2]"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sut Urunleri",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Yogurt",
                            QuickAmounts = "[250,500,1000]"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kahvaltilik",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Peynir",
                            QuickAmounts = "[100,250,500]"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Kahvaltilik",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Tereyagi",
                            QuickAmounts = "[100,250,500]"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Et ve Tavuk",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Tavuk",
                            QuickAmounts = "[250,500,1000]"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Et ve Tavuk",
                            DefaultUnit = "gram",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Kiyma",
                            QuickAmounts = "[250,500,1000]"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sebze",
                            DefaultUnit = "adet",
                            IsActive = true,
                            IsQuickAdd = true,
                            Name = "Domates",
                            QuickAmounts = "[2,4,6,8]"
                        });
                });

            modelBuilder.Entity("FridgeApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
